const primaryForexKeywords = [
  "best forex brokers",
  "forex brokers",
  "forex broker",
  "trusted forex brokers",
  "regulated forex brokers",
  "safe forex brokers",
  "forex broker reviews",
  "forex broker comparison",
  "top forex brokers 2026",
  "best forex broker 2026",
  "online forex brokers",
  "forex trading brokers",
  "forex trading platforms",
  "best forex trading platform",
  "currency trading brokers",
  "foreign exchange brokers",
  "global forex brokers",
  "international forex brokers",
  "forex broker ratings",
  "forex broker rankings",
  "forex broker safety",
  "licensed forex brokers",
  "reliable forex brokers",
  "broker trusted forex",
  "forex broker guide",
  "forex broker list",
  "forex broker analysis",
  "forex broker fees",
  "forex broker spreads",
  "forex broker regulation",
  "forex broker licenses",
  "forex brokers for beginners",
  "professional forex brokers",
  "low spread forex brokers",
  "ECN forex brokers",
  "STP forex brokers",
  "market maker forex brokers",
  "high leverage forex brokers",
  "forex bonus brokers",
  "mobile forex brokers",
  "forex news brokers",
  "new forex brokers",
  "forex education",
  "forex trading guide",
  "forex market analysis",
  "technical analysis forex",
  "forex risk management",
  "forex trading strategies",
  "forex trading for beginners",
  "forex CFD brokers",
];

const secondaryForexKeywords = [
  "FCA regulated forex brokers",
  "CySEC regulated forex brokers",
  "ASIC regulated forex brokers",
  "CFTC regulated forex brokers",
  "NFA regulated forex brokers",
  "FSCA regulated brokers",
  "DFSA regulated forex brokers",
  "tier one regulated brokers",
  "multi regulated forex broker",
  "broker investor protection",
  "segregated client funds brokers",
  "negative balance protection brokers",
  "forex broker trust score",
  "forex broker due diligence",
  "forex broker verification",
  "forex broker scam check",
  "avoid forex scams",
  "transparent forex brokers",
  "independent broker reviews",
  "real account broker testing",
  "broker withdrawal testing",
  "broker execution testing",
  "broker slippage analysis",
  "broker spread comparison",
  "broker commission comparison",
  "broker fee comparison",
  "forex account types",
  "standard forex account",
  "raw spread account",
  "zero spread account",
  "cent account forex broker",
  "Islamic forex account",
  "swap free forex account",
  "demo account forex broker",
  "copy trading brokers",
  "social trading brokers",
  "PAMM account brokers",
  "MAM account brokers",
  "API trading brokers",
  "VPS forex brokers",
  "scalping forex brokers",
  "day trading forex brokers",
  "swing trading forex brokers",
  "algorithmic trading brokers",
  "MetaTrader 4 brokers",
  "MetaTrader 5 brokers",
  "cTrader brokers",
  "TradingView forex brokers",
  "mobile trading app brokers",
  "iOS forex trading app",
  "Android forex trading app",
  "forex broker customer support",
  "broker deposit methods",
  "broker withdrawal speed",
  "fast withdrawal forex brokers",
  "low minimum deposit brokers",
  "forex broker education",
  "forex broker research tools",
  "economic calendar forex",
  "forex signals broker",
  "forex market sentiment",
  "major currency pairs",
  "EUR USD trading brokers",
  "GBP USD trading brokers",
  "USD JPY trading brokers",
  "gold trading brokers",
  "CFD trading brokers",
  "commodities trading brokers",
  "indices CFD brokers",
  "crypto CFD brokers",
  "spread betting brokers",
  "forex liquidity providers",
  "NDD forex brokers",
  "no dealing desk brokers",
  "direct market access forex",
  "raw spreads forex",
  "institutional forex execution",
  "retail forex brokers",
  "professional trading accounts",
  "forex leverage comparison",
  "forex margin requirements",
  "broker risk warning",
  "forex trading costs",
  "forex platform comparison",
  "forex broker methodology",
  "broker editorial review",
  "forex broker pros and cons",
  "best brokers by category",
  "regulated brokers comparison",
  "trusted trading platforms",
  "secure forex trading",
];

const longTailForexKeywords = [
  "how to choose a trusted forex broker in 2026",
  "best regulated forex brokers for beginners 2026",
  "safest forex brokers with FCA regulation",
  "forex brokers with CySEC and ASIC licenses",
  "forex broker reviews with real account testing",
  "compare forex brokers by spreads and fees",
  "compare forex brokers by regulation and safety",
  "lowest spread forex brokers for EUR USD trading",
  "best low spread forex brokers for scalping",
  "best ECN forex brokers with raw spreads",
  "best STP brokers with no dealing desk execution",
  "best market maker brokers for beginner traders",
  "best forex brokers with fast withdrawals",
  "best forex brokers with low minimum deposit",
  "best forex brokers with demo accounts",
  "best forex brokers with negative balance protection",
  "best forex brokers with segregated client funds",
  "best forex brokers for mobile trading apps",
  "best forex brokers for MetaTrader 4",
  "best forex brokers for MetaTrader 5",
  "best forex brokers for cTrader platform",
  "best forex brokers for TradingView charts",
  "best forex brokers for copy trading",
  "best forex brokers for social trading",
  "best forex brokers for professional traders",
  "best forex brokers for high volume traders",
  "best forex brokers for algorithmic trading",
  "best forex brokers for automated trading strategies",
  "best forex brokers for day trading",
  "best forex brokers for swing trading",
  "best forex brokers for scalping strategies",
  "best forex brokers for gold and forex CFDs",
  "best forex brokers for major currency pairs",
  "best forex brokers for exotic currency pairs",
  "best forex brokers for high leverage trading",
  "high leverage forex brokers with regulation",
  "regulated forex brokers that allow scalping",
  "regulated forex brokers with low commissions",
  "regulated forex brokers with tight spreads",
  "regulated forex brokers with swap free accounts",
  "regulated forex brokers with Islamic accounts",
  "regulated forex brokers with cent accounts",
  "regulated forex brokers with VPS hosting",
  "regulated forex brokers with API access",
  "regulated forex brokers with fast execution",
  "forex broker comparison for trading costs",
  "forex broker comparison for execution speed",
  "forex broker comparison for account types",
  "forex broker comparison for payment methods",
  "forex broker comparison for customer support",
  "forex broker comparison for investor protection",
  "forex broker comparison for platform features",
  "forex broker comparison for beginners",
  "forex broker comparison for professionals",
  "forex broker comparison for mobile traders",
  "forex broker comparison for raw spread accounts",
  "forex broker comparison for standard accounts",
  "forex broker comparison for commission accounts",
  "forex broker comparison for bonus offers",
  "forex broker comparison for education resources",
  "forex broker comparison for market research",
  "forex broker comparison for economic calendar tools",
  "forex broker comparison for risk management tools",
  "forex broker comparison for charting tools",
  "forex broker comparison for order types",
  "forex broker comparison for slippage and requotes",
  "forex broker comparison for deposit and withdrawal fees",
  "forex broker comparison for overnight swap fees",
  "forex broker comparison for inactivity fees",
  "forex broker comparison for spreads on EUR USD",
  "forex broker comparison for spreads on GBP USD",
  "forex broker comparison for spreads on USD JPY",
  "forex broker comparison for spreads on XAU USD",
  "forex broker reviews for IC Markets",
  "forex broker reviews for Exness",
  "forex broker reviews for Pepperstone",
  "forex broker reviews for XM",
  "forex broker reviews for OANDA",
  "forex broker reviews for AvaTrade",
  "forex broker reviews for Tickmill",
  "forex broker reviews for FP Markets",
  "forex broker reviews for FXTM",
  "forex broker reviews for HFM",
  "complete guide to forex trading in 2026",
  "forex trading roadmap for beginners 2026",
  "forex trading guide for new traders",
  "forex trading risk management for beginners",
  "how much risk per forex trade",
  "how to protect capital in forex trading",
  "how to build a forex trading plan",
  "how to read forex charts for beginners",
  "how to use technical analysis in forex",
  "how to use support and resistance in forex",
  "how to use moving averages in forex",
  "how to use RSI in forex trading",
  "how to use MACD in forex trading",
  "how to trade forex news safely",
  "how to understand forex spreads and pips",
  "how to understand forex leverage and margin",
  "how to test a forex strategy on demo account",
  "how to evaluate forex broker regulation",
  "how to verify if a forex broker is regulated",
  "how to avoid unregulated forex brokers",
  "how to compare forex brokers before opening account",
  "what makes a forex broker trustworthy",
  "what is an ECN forex broker",
  "what is an STP forex broker",
  "what is a market maker forex broker",
  "what is negative balance protection in forex",
  "what are raw spreads in forex trading",
  "what are forex broker commissions",
  "what are forex broker swap fees",
  "what are the safest forex brokers",
  "what are the best forex brokers for beginners",
  "which forex brokers have the best spreads",
  "which forex brokers are best for mobile trading",
  "which forex brokers are best for professional traders",
  "which forex brokers offer demo accounts",
  "which forex brokers offer fast withdrawals",
  "which forex brokers offer high leverage safely",
  "melhores corretoras forex 2026",
  "corretoras forex confiáveis",
  "corretoras forex regulamentadas",
  "corretoras forex seguras",
  "análise de corretoras forex",
  "comparar corretoras forex",
  "corretoras forex com menor spread",
  "corretoras forex para iniciantes",
  "corretoras forex com conta demo",
  "corretoras forex com saque rápido",
  "corretoras forex com alavancagem alta",
  "corretoras forex ECN",
  "corretoras forex STP",
  "guia de trading forex 2026",
  "gestão de risco no forex",
  "análise técnica forex",
  "como escolher uma corretora forex segura",
  "como verificar regulamentação de corretora forex",
  "melhores brokers forex 2026",
  "brokers forex confiáveis",
];

const pageKeywordClusters: Record<string, string[]> = {
  "/": [
    "trusted broker rankings",
    "best forex broker comparison 2026",
    "safe trading partner reviews",
    "verified regulated forex brokers",
    "forex broker trust methodology",
  ],
  "/best-forex-brokers": [
    "top rated forex brokers 2026",
    "best overall forex brokers",
    "forex broker ranking table",
    "best regulated forex broker list",
    "highest rated forex brokers",
  ],
  "/broker-reviews": [
    "professional forex broker reviews",
    "real money broker testing",
    "broker review methodology",
    "independent broker analysis",
    "forex broker pros and cons",
  ],
  "/trading-guides": [
    "forex trading education 2026",
    "complete forex trading guide 2026",
    "forex learning path",
    "forex trading tutorials",
    "forex strategy guide for beginners",
  ],
  "/market-analysis": [
    "forex market analysis 2026",
    "currency pair analysis",
    "technical forex forecast",
    "economic calendar trading",
    "forex market sentiment analysis",
  ],
  "/best-spreads": [
    "low spread forex brokers",
    "tight spread broker comparison",
    "lowest trading cost forex brokers",
    "raw spread broker accounts",
    "best spreads for scalping",
  ],
  "/ecn-brokers": [
    "ECN forex broker comparison",
    "raw spread ECN accounts",
    "direct market access forex brokers",
    "no dealing desk ECN brokers",
    "interbank pricing forex brokers",
  ],
  "/stp-brokers": [
    "STP forex broker comparison",
    "straight through processing brokers",
    "NDD STP forex brokers",
    "liquidity provider execution",
    "transparent STP execution",
  ],
  "/market-makers": [
    "market maker forex broker comparison",
    "dealing desk broker guide",
    "fixed spread market maker brokers",
    "market maker execution model",
    "trusted dealing desk brokers",
  ],
  "/best-for-beginners": [
    "beginner friendly forex brokers",
    "forex brokers with demo accounts",
    "low deposit forex brokers",
    "easy forex platforms for beginners",
    "forex education for new traders",
  ],
  "/best-for-professionals": [
    "professional forex broker accounts",
    "institutional execution forex brokers",
    "high volume forex trading brokers",
    "advanced forex trading tools",
    "API trading forex brokers",
  ],
  "/best-mobile-apps": [
    "best forex mobile apps 2026",
    "mobile trading app comparison",
    "iOS forex broker apps",
    "Android forex broker apps",
    "trade forex on mobile safely",
  ],
  "/highest-leverage": [
    "high leverage forex broker comparison",
    "regulated high leverage brokers",
    "forex margin and leverage guide",
    "professional leverage forex accounts",
    "safe high leverage forex trading",
  ],
  "/best-bonuses": [
    "forex broker bonus comparison",
    "welcome bonus forex brokers",
    "deposit bonus broker offers",
    "no deposit forex bonus guide",
    "broker promotion terms and conditions",
  ],
  "/new-brokers": [
    "new forex brokers 2026",
    "recently launched regulated brokers",
    "emerging forex trading platforms",
    "new broker safety checks",
    "new forex broker reviews",
  ],
  "/news": [
    "forex broker news 2026",
    "forex regulation news",
    "broker industry updates",
    "trading platform news",
    "forex market news brokers",
  ],
  "/blog": [
    "forex trading blog",
    "forex education articles",
    "broker comparison articles",
    "forex strategy articles",
    "trading risk management articles",
  ],
};

import { longTailAll } from "./seoLongTail";

export const getSeoKeywords = (path = "/", suppliedKeywords: string[] = []) => {
  const normalizedPath = path === "" ? "/" : path.replace(/\/$/, "") || "/";
  const pageKeywords = pageKeywordClusters[normalizedPath] || [];

  return Array.from(
    new Set([
      ...suppliedKeywords,
      ...pageKeywords,
      ...primaryForexKeywords,
      ...secondaryForexKeywords,
      ...longTailForexKeywords,
      ...longTailAll,
    ]),
  );
};

export const getPageKeywordHighlights = (path = "/") => {
  const normalizedPath = path === "" ? "/" : path.replace(/\/$/, "") || "/";
  return pageKeywordClusters[normalizedPath] || primaryForexKeywords.slice(0, 12);
};
