// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fztzqyetyzpnhtxatrlq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6dHpxeWV0eXpwbmh0eGF0cmxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMDYyOTksImV4cCI6MjA3NDU4MjI5OX0.n4im-2rH33eKOL1C4I3UqP0Ark6qPAbZqEyD-UYASzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});